/*
 * Copyright 2026 Darshan Patel
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

const { mapScope } = require('../mappings');
const presets = require('../presets');

function processVimMarker(str) {
    if (!str) return '';
    return presets.escape(str).replace(/ /g, '\\s*');
}

/**
 * Generates a Vim syntax file (.vim).
 * @param {object} grammar 
 * @returns {string}
 */
function generateVim(grammar) {
    const lang = grammar.name.toLowerCase().replace(/\s+/g, '_');
    let includes = "";
    let rulesOutput = "";
    const injectedSyntaxes = new Set();

    grammar.rules.forEach((r, i) => {
        const id = `LexLoom_${i}`;
        const vimGroup = mapScope(r.universalScope, 'vim');
        let ruleOutput = "";

        // Handle language injection
        const injections = Array.isArray(r.injectLanguage) ? r.injectLanguage : (r.injectLanguage ? [r.injectLanguage] : []);
        let containsClause = "";
        const clusters = [];

        injections.forEach(inj => {
            if (inj.vimSyntax) {
                const vLang = inj.vimSyntax;
                const clusterName = `LexLoomCluster_${vLang.toUpperCase()}`;
                if (!injectedSyntaxes.has(vLang)) {
                    includes += `syn include @${clusterName} syntax/${vLang}.vim\n`;
                    injectedSyntaxes.add(vLang);
                }
                clusters.push(`@${clusterName}`);
            }
        });

        if (clusters.length > 0) {
            containsClause = ` contains=${clusters.join(',')}`;
        }

        switch (r.ruleType) {
            case 'wordList':
                ruleOutput += `syntax keyword ${id} ${r.words.join(' ')}\n`;
                break;
            case 'symbolList':
                // Individual match lines for each symbol with Vim-specific escaping
                r.symbols.forEach(sym => {
                    ruleOutput += `syntax match ${id} "${vimRegex(vimEscapeSymbol(sym))}"\n`;
                });
                break;
            case 'preset':
                const presetMap = {
                    'number.decimal': '\\(\\k\\)\\@<!\\([+-]\\)\\?[0-9]\\+\\>',
                    'number.hex': '\\(\\k\\)\\@<!\\([+-]\\)\\?0[xX][0-9a-fA-F]\\+\\>',
                    'number.binary': '\\(\\k\\)\\@<!\\([+-]\\)\\?0[bB][01]\\+\\>',
                    'number.octal': '\\(\\k\\)\\@<!\\([+-]\\)\\?0[oO]\\?[0-7]\\+\\>'
                };
                const pattern = presetMap[r.presetId] || '';
                if (pattern) {
                    ruleOutput += `syntax match ${id} "${pattern}"\n`;
                }
                break;
            case 'lineMarker':
                ruleOutput += `syntax match ${id} "${vimRegex(`${processVimMarker(r.start)}.*`)}"\n`;
                break;
            case 'blockMarker':
                ruleOutput += `syntax region ${id} start="${vimRegex(processVimMarker(r.start))}" end="${vimRegex(processVimMarker(r.end))}"${containsClause}\n`;
                break;
            case 'stringMarker':
                const skipStr = r.escapeChar ? ` skip="\\\\\\\\|\\\\\\\""` : "";
                ruleOutput += `syntax region ${id} start="${vimRegex(processVimMarker(r.quote))}" end="${vimRegex(processVimMarker(r.quote))}"${skipStr}${containsClause}\n`;
                break;
        }

        if (ruleOutput) {
            rulesOutput += ruleOutput;
            if (vimGroup) {
                rulesOutput += `highlight default link ${id} ${vimGroup}\n\n`;
            }
        }
    });

    let output = `" Vim syntax file\n" Language: ${grammar.name}\n" Generated by LexLoom\n\n`;
    output += `if exists("b:current_syntax")\n  finish\nendif\n\n`;
    output += includes + (includes ? "\n" : "");
    output += rulesOutput;
    output += `let b:current_syntax = "${lang}"\n`;

    return output;
}

/**
 * Vim-specific escaping for symbols.
 * + and | are literal by default.
 * *, ., ^, $, ~, [, ] are escaped.
 */
function vimEscapeSymbol(str) {
    if (!str) return '';
    // Escape *, ., ^, $, ~, [, ]
    return str.replace(/[*.^$~[\]]/g, '\\$&');
}

/**
 * Basic conversion for Vim's regex flavor.
 */
function vimRegex(regex) {
    // Escape backslashes and quotes for the Vim command string
    // Standard Vim regex treats + as literal, so we escape it to \+ for "1 or more"
    // However, when we want a literal +, we should NOT escape it.
    // This function is used for general rules. for symbolList, we use vimEscapeSymbol first.
    return regex.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
}

module.exports = generateVim;
